# Generated by Django 4.0 on 2021-12-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='onePiece',
            fields=[
                ('Char_id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.PositiveIntegerField()),
                ('Roles', models.CharField(max_length=40)),
                ('Power', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'OnePiece',
                'verbose_name_plural': 'OnePieces',
            },
        ),
    ]
