# Generated by Django 4.0 on 2021-12-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allOneProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onepiece',
            name='Char_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
